netG:
  input:
    kernel_size: 9
    stride: 1
    padding: 4

  output:
    kernel_size: 9
    stride: 1
    padding: 4

  block:
    kernel_size: 3
    stride: 1
    padding: 1
    residual: 16
    upscale_factor: 2
